"""Flight retrieval: HyDE expansion, Qdrant vector search, and filter construction.

Retrieval pipeline
------------------
For each query, search_flights_hybrid executes the following stages:

1. HyDE expansion — one or more hypothetical flight documents are generated by
   the LLM and embedded.  The resulting vector(s) land closer to real flight
   records in embedding space than a raw query embedding would, improving recall
   for under-specified queries ("cheap morning flight" vs. a full record string).

2. Qdrant ANN search — cosine similarity search with optional hard filters
   (origin, dest, carrier, month range, time-of-day band).  When filters drop
   all results they are retried without filters and filters_dropped=True is
   signalled so the caller can inform the user.

3. Cross-encoder reranking (optional) — when ENABLE_RERANKER=true, RERANK_FETCH_K
   candidates are retrieved and passed to app.rag.reranker.rerank, which scores
   each (query, flight_doc) pair jointly and returns the top RERANK_RETURN_N.

Multi-sample HyDE
-----------------
When HYDE_NUM_SAMPLES > 1, n independent LLM calls generate n hypothetical
documents that are embedded and averaged (centroid in embedding space).
Centroid HyDE improves recall on ambiguous queries by reducing sensitivity to
any single generation artefact.  Each sample bypasses the document cache (which
would otherwise return the same string for every call); the cached path is used
only when HYDE_NUM_SAMPLES == 1.

On a single-GPU Ollama instance the n LLM calls are serialised by the inference
server despite being dispatched concurrently via asyncio.gather.  Wall-clock
latency for multi-sample HyDE is therefore approximately n × single_hyde_latency.

Latency instrumentation
------------------------
Each call to search_flights_hybrid records per-stage wall-clock times in the
OTel span attributes (latency_hyde_ms, latency_embed_ms, latency_qdrant_ms,
latency_rerank_ms).  These are the primary inputs for the latency benchmarks in
scripts/eval_retrieval.py and for threshold calibration decisions.

Caching
-------
The HyDE document cache is two-tiered:
  - Per-process dict: O(1) hit, eviction is FIFO at 256 slots.
  - Redis (when REDIS_URL is configured): O(1) network hop, shared across
    workers, TTL = HYDE_CACHE_TTL seconds.

Only n=1 HyDE uses the cache.  Multi-sample bypasses it intentionally so that
each sample is an independent draw from the LLM's distribution.
"""
from __future__ import annotations

import asyncio
import logging
import time
from typing import Any, Optional

from qdrant_client.http import models as qm

from app.core.config import settings
from app.rag.qdrant_client import get_qdrant
from app.rag.embeddings import async_embed_text, async_embed_texts
from app.rag.flight_doc import HYDE_PROMPT

log = logging.getLogger(__name__)

_FLIGHT_FIELDS = [
    "flight_id", "carrier", "flight", "origin", "dest",
    "sched_dep_time", "sched_arr_time", "dep_time", "arr_time",
    "distance", "air_time", "year", "month", "day",
]

_hyde_cache: dict[str, str] = {}
_HYDE_CACHE_MAX = 256

_TIME_BANDS: dict[str, tuple[int, int]] = {
    "early_morning": (0, 559),
    "morning": (600, 1159),
    "afternoon": (1200, 1759),
    "evening": (1800, 2159),
    "late_night": (2200, 2359),
}


async def _hyde_query(query: str) -> str:
    """Return a hypothetical flight document for HyDE retrieval, with two-tier caching.

    Checks the per-process dict first (microseconds), then Redis (milliseconds),
    then falls back to LLM inference.  Cross-worker cache hits in multi-process
    deployments require REDIS_URL to be configured.

    Args:
        query: Natural-language flight search query.

    Returns:
        Synthetic flight-record string matching the indexed doc format,
        or the original query on LLM failure.
    """
    if query in _hyde_cache:
        return _hyde_cache[query]

    from app.core.redis_client import get_redis
    redis = await get_redis()
    if redis is not None:
        cached = await redis.get(f"hyde:{query}")
        if cached:
            _set_local_cache(query, cached)
            return cached

    from app.core.tracing import get_tracer
    with get_tracer().start_as_current_span("hyde.generate") as span:
        span.set_attribute("query.text", query[:200])
        result = await _hyde_query_uncached(query)
        span.set_attribute("hyde.fallback", result == query)

    _set_local_cache(query, result)
    if redis is not None:
        await redis.setex(f"hyde:{query}", settings.HYDE_CACHE_TTL, result)

    return result


def _set_local_cache(query: str, value: str) -> None:
    if len(_hyde_cache) >= _HYDE_CACHE_MAX:
        _hyde_cache.pop(next(iter(_hyde_cache)))
    _hyde_cache[query] = value


async def _hyde_query_uncached(query: str) -> str:
    """Generate one hypothetical flight document from the LLM without caching.

    Args:
        query: Natural-language flight search query.

    Returns:
        Synthetic single-line flight record, or the original query on failure.
    """
    from app.core.http_client import get_http_client
    try:
        r = await get_http_client().post(
            f"{settings.OLLAMA_BASE_URL.rstrip('/')}/api/chat",
            json={
                "model": settings.OLLAMA_CHAT_MODEL,
                "messages": [{"role": "user", "content": HYDE_PROMPT.format(query=query)}],
                "stream": False,
            },
        )
        r.raise_for_status()
        raw = r.json().get("message", {}).get("content", "").strip()
        if not raw:
            return query
        for line in raw.splitlines():
            line = line.strip()
            if "->" in line and len(line) > 20:
                return line
        return raw.splitlines()[-1].strip() or query
    except Exception:
        log.warning("HyDE query failed for %r, falling back to raw query", query)
        return query


async def _hyde_embed(query: str, n_samples: int) -> list[float]:
    """Embed a query via HyDE, optionally averaging over multiple independent samples.

    With n_samples=1, the HyDE document is fetched from the two-tier cache and
    a single embedding is returned.  With n_samples>1, n independent LLM calls
    are made (bypassing the cache for diversity), all documents are embedded in
    one batched request, and the embeddings are averaged to form the centroid
    vector.

    Args:
        query: Natural-language flight search query.
        n_samples: Number of independent hypothetical documents to generate.
            1 uses the cache; >1 always calls the LLM n times.

    Returns:
        Embedding vector (centroid when n_samples > 1).
    """
    if n_samples == 1:
        doc = await _hyde_query(query)
        return await async_embed_text(doc)

    docs = await asyncio.gather(*(_hyde_query_uncached(query) for _ in range(n_samples)))
    vecs = await async_embed_texts(list(docs))
    dim = len(vecs[0])
    return [sum(v[i] for v in vecs) / n_samples for i in range(dim)]


def _build_filter(
    origin: str | None,
    dest: str | None,
    carrier: str | None,
    year: int | None,
    month: int | None,
    day: int | None,
    flight: int | None,
    month_min: int | None = None,
    month_max: int | None = None,
    time_of_day: str | None = None,
) -> qm.Filter | None:
    """Build a Qdrant payload filter from optional fields.

    Supports exact-match keyword filters, integer equality, month ranges via
    Qdrant Range conditions, and departure time bands (also Range on sched_dep_time).

    Args:
        origin: IATA origin code.
        dest: IATA destination code.
        carrier: Carrier code.
        year: Year.
        month: Exact month (1-12). Mutually exclusive with month_min/month_max.
        day: Day of month.
        flight: Flight number.
        month_min: Start of month range (1-12), inclusive.
        month_max: End of month range (1-12), inclusive.
        time_of_day: Named departure band — see _TIME_BANDS.

    Returns:
        A Qdrant Filter, or None if no constraints are provided.
    """
    must = []
    if origin:
        must.append(qm.FieldCondition(key="origin", match=qm.MatchValue(value=origin.upper())))
    if dest:
        must.append(qm.FieldCondition(key="dest", match=qm.MatchValue(value=dest.upper())))
    if carrier:
        must.append(qm.FieldCondition(key="carrier", match=qm.MatchValue(value=carrier.upper())))
    if year is not None:
        must.append(qm.FieldCondition(key="year", match=qm.MatchValue(value=int(year))))
    if month is not None:
        must.append(qm.FieldCondition(key="month", match=qm.MatchValue(value=int(month))))
    if day is not None:
        must.append(qm.FieldCondition(key="day", match=qm.MatchValue(value=int(day))))
    if flight is not None:
        must.append(qm.FieldCondition(key="flight", match=qm.MatchValue(value=int(flight))))

    if month_min is not None or month_max is not None:
        must.append(qm.FieldCondition(
            key="month",
            range=qm.Range(gte=month_min, lte=month_max),
        ))

    if time_of_day and time_of_day in _TIME_BANDS:
        lo, hi = _TIME_BANDS[time_of_day]
        must.append(qm.FieldCondition(
            key="sched_dep_time",
            range=qm.Range(gte=lo, lte=hi),
        ))

    return qm.Filter(must=must) if must else None


def _point_to_dict(p: Any) -> dict:
    payload = getattr(p, "payload", None) or {}
    return {
        "flight_id": str(getattr(p, "id", "")),
        "score": float(p.score) if getattr(p, "score", None) is not None else None,
        **{k: payload.get(k) for k in _FLIGHT_FIELDS if k != "flight_id"},
    }


def _vector_search_sync(
    client: Any,
    vec: list[float],
    flt: qm.Filter | None,
    limit: int,
    score_threshold: float,
) -> list[dict]:
    results = client.query_points(
        collection_name=settings.QDRANT_FLIGHTS_COLLECTION,
        query=vec,
        limit=limit,
        query_filter=flt,
        score_threshold=score_threshold,
        with_payload=True,
        with_vectors=False,
    )
    return [_point_to_dict(p) for p in results.points]


async def search_flights_hybrid(
    query: str,
    origin: Optional[str] = None,
    dest: Optional[str] = None,
    carrier: Optional[str] = None,
    year: Optional[int] = None,
    month: Optional[int] = None,
    day: Optional[int] = None,
    flight: Optional[int] = None,
    month_min: Optional[int] = None,
    month_max: Optional[int] = None,
    time_of_day: Optional[str] = None,
    limit: int = 10,
    score_threshold: Optional[float] = None,
    hyde_num_samples: Optional[int] = None,
) -> dict:
    """Search flights using HyDE-expanded embeddings with hard-filter fallback.

    When ENABLE_RERANKER is true, fetches RERANK_FETCH_K candidates from Qdrant
    and applies a cross-encoder before returning the top RERANK_RETURN_N results.

    Per-stage wall-clock timings are attached to the OTel span as
    latency_hyde_ms, latency_embed_ms, latency_qdrant_ms, and latency_rerank_ms.
    These are surfaced by eval_retrieval.py for latency benchmarking.

    Args:
        query: Natural-language description of the desired flight.
        origin: IATA origin code filter.
        dest: IATA destination code filter.
        carrier: Carrier code filter.
        year: Year filter.
        month: Exact month filter (1-12).
        day: Day-of-month filter.
        flight: Flight number filter.
        month_min: Start of month range, inclusive.
        month_max: End of month range, inclusive.
        time_of_day: Departure time band name.
        limit: Maximum results to return (after reranking if enabled).
        score_threshold: Override settings.RETRIEVAL_SCORE_THRESHOLD for this call.
        hyde_num_samples: Override settings.HYDE_NUM_SAMPLES for this call.
            Used by eval_retrieval.py to run HyDE A/B comparisons without
            mutating global config.

    Returns:
        Dict with keys:
            results (list[dict]): Matched flight records, scored and sorted.
            filters_dropped (bool): True when the filtered query returned no
                results and was retried without filters.
            latency (dict): Per-stage timings in milliseconds (hyde_ms,
                embed_ms, qdrant_ms, rerank_ms, total_ms).
    """
    from app.core.tracing import get_tracer

    effective_threshold = score_threshold if score_threshold is not None else settings.RETRIEVAL_SCORE_THRESHOLD
    n_samples = hyde_num_samples if hyde_num_samples is not None else settings.HYDE_NUM_SAMPLES
    fetch_k = settings.RERANK_FETCH_K if settings.ENABLE_RERANKER else limit

    latency: dict[str, float] = {}

    with get_tracer().start_as_current_span("retrieval.search") as span:
        span.set_attribute("query.text", query[:200])
        span.set_attribute("query.limit", limit)
        span.set_attribute("reranker.enabled", settings.ENABLE_RERANKER)
        span.set_attribute("hyde.num_samples", n_samples)

        client = get_qdrant()
        flt = _build_filter(origin, dest, carrier, year, month, day, flight, month_min, month_max, time_of_day)

        t0 = time.perf_counter()
        vec = await _hyde_embed(query, n_samples)
        latency["hyde_ms"] = (time.perf_counter() - t0) * 1000

        t1 = time.perf_counter()
        points = await asyncio.to_thread(_vector_search_sync, client, vec, flt, fetch_k, effective_threshold)
        latency["qdrant_ms"] = (time.perf_counter() - t1) * 1000

        filters_dropped = False
        if not points and flt is not None:
            points = await asyncio.to_thread(_vector_search_sync, client, vec, None, fetch_k, effective_threshold)
            filters_dropped = True
            span.set_attribute("filters_dropped", True)

        t2 = time.perf_counter()
        if settings.ENABLE_RERANKER and points:
            from app.rag.reranker import rerank
            return_n = min(settings.RERANK_RETURN_N, limit)
            points = await rerank(query, points, top_n=return_n)
            latency["rerank_ms"] = (time.perf_counter() - t2) * 1000
        else:
            points = points[:limit]
            latency["rerank_ms"] = 0.0

        latency["total_ms"] = sum(latency.values())

        span.set_attribute("result_count", len(points))
        span.set_attribute("latency_hyde_ms", round(latency["hyde_ms"], 1))
        span.set_attribute("latency_qdrant_ms", round(latency["qdrant_ms"], 1))
        span.set_attribute("latency_rerank_ms", round(latency["rerank_ms"], 1))

        return {"results": points, "filters_dropped": filters_dropped, "latency": latency}


async def get_flight_by_id(flight_id: str) -> dict | None:
    """Retrieve a single flight record by its UUID.

    Args:
        flight_id: UUID string of the flight point in Qdrant.

    Returns:
        Dict of flight fields with ``flight_id`` injected, or None if not found.
    """
    client = get_qdrant()
    pts = await asyncio.to_thread(
        lambda: client.retrieve(
            collection_name=settings.QDRANT_FLIGHTS_COLLECTION,
            ids=[flight_id],
            with_payload=True,
            with_vectors=False,
        )
    )
    if not pts:
        return None
    p = pts[0]
    payload = p.payload or {}
    payload["flight_id"] = str(p.id)
    return payload
